# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('large', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('binding', models.CharField(max_length=20)),
                ('salesrank', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=30)),
                ('is_adult_product', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark_search.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark_search.Language'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark_search.ProductGroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark_search.Publisher'),
        ),
    ]
